import type {
  AIGenerationRequest,
  AIGenerationResult,
  AIProvider,
} from "@/server/services/ai/provider.interface";

/**
 * Deterministic in-process AI provider for unit tests and `MUSEFLOW_AI_PROVIDER=fake`.
 *
 * Behavior:
 * - Returns a deterministic { title, body } keyed by mode + inputs.
 * - If any input text contains the literal `TRIGGER_REJECT` the title and body
 *   echo it back; the moderation fake will then reject — letting tests cover
 *   the safety-rejection branch end-to-end without a real provider.
 * - Token counts mimic OpenAI shape (~4 chars per token).
 * - `errorOnNextCall` lets tests force `AIProviderError` once.
 */
export class FakeAIProvider implements AIProvider {
  readonly name = "fake";
  readonly model = "fake-model-1";

  /** Set to true via `failNext()` to force the next call to throw. */
  private failNext = false;

  failNextCall(): void {
    this.failNext = true;
  }

  async generate(req: AIGenerationRequest): Promise<AIGenerationResult> {
    if (this.failNext) {
      this.failNext = false;
      throw new Error("[fake-ai-provider] forced failure");
    }

    const output = renderOutput(req);
    const approxTokens = (s: string) => Math.max(1, Math.ceil(s.length / 4));
    const inputText = inputTextFor(req);

    return {
      output,
      inputTokens: approxTokens(inputText),
      outputTokens: approxTokens(output.title) + approxTokens(output.body),
      rawProvider: this.name,
      rawModel: this.model,
    };
  }
}

function inputTextFor(req: AIGenerationRequest): string {
  switch (req.mode) {
    case "CREATE":
      return `${req.idea} (tone=${req.tone})`;
    case "REWRITE":
    case "CONTINUE":
    case "SUMMARIZE":
      return `${req.source.title}\n\n${req.source.body}`;
    case "CHANGE_TONE":
      return `${req.source.title}\n\n${req.source.body}\n(target=${req.targetTone})`;
  }
}

function renderOutput(req: AIGenerationRequest): { title: string; body: string } {
  switch (req.mode) {
    case "CREATE": {
      const trigger = req.idea.includes("TRIGGER_REJECT");
      return {
        title: trigger ? "TRIGGER_REJECT title" : `On ${truncate(req.idea, 60)}`,
        body: trigger
          ? "TRIGGER_REJECT body"
          : `${capitalize(req.tone)} take on the idea: ${req.idea}.\n\nGenerated by the fake provider for tests.`,
      };
    }
    case "REWRITE":
      return {
        title: `${req.source.title} (rewrite)`,
        body: `Rewritten: ${req.source.body}`,
      };
    case "CONTINUE":
      return {
        title: req.source.title,
        body: `${req.source.body}\n\n— continued by the fake provider.`,
      };
    case "SUMMARIZE":
      return {
        title: `Summary: ${req.source.title}`,
        body: `In short: ${truncate(req.source.body, 240)}`,
      };
    case "CHANGE_TONE":
      return {
        title: `${req.source.title} (${req.targetTone.toLowerCase()})`,
        body: `${req.source.body}\n\n— retoned to ${req.targetTone}.`,
      };
  }
}

function truncate(s: string, max: number): string {
  return s.length <= max ? s : s.slice(0, max - 1) + "…";
}

function capitalize(s: string): string {
  if (s.length === 0) return s;
  return s[0]!.toUpperCase() + s.slice(1).toLowerCase();
}
